#ifndef HAVE_NODE_DFA
#define HAVE_NODE_DFA

#include "nodes.h"

/* these functions are automatically generated by node-dfa.py */

extern char *node2str(enum node node);

/* equivalent to strlen(node2str(node)), but faster */
extern int nodelen(enum node node);

/* finds the first node in str and returns the rest of the string after that
 * node. returns NULL on unknown node. */
extern char *str2node(char *str, enum node *ret);

#endif
